name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            output: dyno-rdg-linux
          - os: windows-latest
            output: dyno-rdg-windows.exe
          - os: macos-latest
            output: dyno-rdg-mac
      fail-fast: true  # ← don't cancel other platforms if one fails

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4.2.2

      - uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt nuitka ordered-set zstandard

      - name: Install Linux system deps
        if: runner.os == 'Linux'
        run: sudo apt-get install -y gcc patchelf python3-tk

      - name: Install Mac system deps
        if: runner.os == 'macOS'
        run: brew install python-tk

      - name: Build Linux/Mac
        if: runner.os != 'Windows'
        run: |
          python -m nuitka \
          --standalone \
          --onefile  \
          --nofollow-import-to=IPython \
          --noinclude-default-mode=error \
          --nofollow-import-to=doctest \
          --enable-plugin=tk-inter \
          --static-libpython=no \
          --include-package-data=dynordg \
          --include-package=matplotlib.backends \
          --output-filename=${{ matrix.output }} \
          dynordg_app.py


      - name: Build Windows
        if: runner.os == 'Windows'
        run: |
          python -m nuitka `
            --standalone `
            --assume-yes-for-downloads `
            --onefile  `
            --nofollow-import-to=IPython `
            --noinclude-default-mode=error `
            --nofollow-import-to=doctest `
            --enable-plugin=tk-inter `
            --static-libpython=no `
            --include-package-data=dynordg `
            --include-package=matplotlib.backends `
            --output-filename=${{ matrix.output }} `
            dynordg_app.py

      - name: Upload to release
        uses: softprops/action-gh-release@v2.3.2
        with:
          files: ${{ matrix.output }}
